[complaints-context]
exten => 100,1,Answer()
 same => n,Wait(1)
 same => n,Playback(/opt/complaints-hotline/audio_prompts/welcome)
 same => n,PlayTones(beep)
 same => n,Wait(0.5)
 same => n,StopPlayTones()
 same => n,Set(UNIQUE_RECORDING_NAME=${STRFTIME(${EPOCH},,%Y-%m-%d_%H-%M-%S)})
 same => n,Record(/tmp/raw_complaint_${UNIQUE_RECORDING_NAME}:wav,,,k)
 same => n,System(/opt/complaints-hotline/bin/python /opt/complaints-hotline/record_and_process.py /tmp/raw_complaint_${UNIQUE_RECORDING_NAME}.wav ${UNIQUE_RECORDING_NAME}.wav)
 same => n,Hangup()