[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0:5060
tcpenable=no
transport=udp
srvlookup=yes

[retro-phone]
type=friend
host=dynamic
secret=1234
context=complaints-context
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw